---
# plugins: [flowtype]

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings

env:
  node: true
  jest: true

rules:
  no-console: 0 

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module
